// labyrinthine_ferrofluid.glsl
// Rotating horizontal magnetic field drives labyrinthine domain patterns and
// traveling-wave instabilities. This is the OTHER classic ferrofluid phenomenon —
// not spikes but STRIPES and LABYRINTHS, patterns that look like fingerprints,
// brain folds, coral polyps viewed from above.
//
// Physical basis:
//   A field applied TANGENTIALLY (parallel to the surface) does not cause
//   normal-field instability. Instead, it creates in-plane domain patterns:
//   the fluid separates into stripes of high and low magnetization oriented
//   perpendicular to the applied field. When the field ROTATES, these stripes
//   rotate too — but with viscous lag — creating labyrinthine patterns that
//   look like they're alive.
//
//   At the phase boundary between stripe and spike regimes, you get coexistence:
//   isolated soliton-like peaks surrounded by labyrinthine moats.
//
// Parameters:
//   magnetStrength   — field intensity [0..10], default 4.0
//   susceptibility   — fluid response [0.1..5], default 2.5
//   surfaceTension   — stripe width control [0.1..5], default 0.7
//   fieldOscillation — rotation speed [0..5], default 0.8
//   viscosity        — lag behind field rotation [0.1..5], default 1.5
//   labyrinthScale   — spatial scale of pattern [0.5..4], default 1.0

#ifdef GL_ES
precision highp float;
#endif

uniform float time;
uniform vec2  resolution;
uniform float magnetStrength;   // default 4.0
uniform float susceptibility;   // default 2.5
uniform float surfaceTension;   // default 0.7
uniform float fieldOscillation; // default 0.8
uniform float viscosity;        // default 1.5
uniform float labyrinthScale;   // default 1.0

// ─── NOISE ───────────────────────────────────────────────────────────────────
float hash(vec2 v) { return fract(sin(dot(v, vec2(127.1, 311.7))) * 43758.5453); }
float hash1(float n) { return fract(sin(n) * 43758.5453); }

float noise(vec2 v) {
    vec2 i = floor(v), f = fract(v);
    vec2 u = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash(i),          hash(i+vec2(1,0)), u.x),
               mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)), u.x), u.y);
}

float fbm(vec2 v, int oct) {
    float s = 0.0, a = 0.5, freq = 1.0;
    for (int i = 0; i < 8; i++) {
        if (i >= oct) break;
        s += noise(v * freq) * a;
        freq *= 2.07; a *= 0.47;
    }
    return s;
}

// ─── ROTATING FIELD DIRECTION ─────────────────────────────────────────────
// The horizontal field vector H(t) rotates in the plane of the ferrofluid.
// It is applied TANGENTIALLY — no normal component.
// The fluid stripes align ⊥ to H with a viscous lag of angle Δφ.

vec2 fieldDirection(float t) {
    float omega = t * fieldOscillation * 6.2831853;
    return vec2(cos(omega), sin(omega));
}

// The fluid's magnetic order parameter lags behind the field due to viscosity.
// lag = ω * τ_relax, where τ_relax ≈ η/(ρg l_c)
vec2 laggedField(float t) {
    float lag   = fieldOscillation / max(viscosity, 0.1) * 0.4;
    float omega = t * fieldOscillation * 6.2831853;
    return vec2(cos(omega - lag), sin(omega - lag));
}

// ─── LABYRINTHINE DOMAIN PATTERN ─────────────────────────────────────────────
// In a rotating in-plane field, the domain pattern is generated by looking at
// the competition between stripe orientation and local anisotropy.
// We use a reaction-diffusion inspired approach:
//   φ(x,t) = projection of local order onto field direction → stripe score
// Then threshold to create domain walls.

float labyrinthineDomain(vec2 p, float t) {
    vec2 H    = laggedField(t);
    vec2 Hperp = vec2(-H.y, H.x);  // perpendicular to field = stripe direction

    float scale = labyrinthScale * 12.0;

    // Project coordinates onto the stripe coordinate system.
    // Stripes run parallel to H, domain walls perpendicular to H.
    float along = dot(p, H);
    float across = dot(p, Hperp);

    // Base stripe pattern: sinusoidal with the capillary wavelength
    // λ_stripe ∝ surfaceTension^0.5 / magnetStrength
    float stripeK = scale * magnetStrength * 0.5 / max(surfaceTension, 0.1);
    stripeK = clamp(stripeK, 4.0, 30.0);

    float stripe = sin(across * stripeK + fbm(p * 3.0 + H * 2.0, 3) * 2.0);

    // Labyrinthine disorder: the stripes meander due to competing domains.
    // fbm noise rotated by the field direction adds the characteristic
    // "fingerprint" topology.
    float disorder = fbm(p * 5.0 + Hperp * time * fieldOscillation * 0.2, 4);
    float warpedStripe = sin(across * stripeK +
                             along * 1.5 +
                             disorder * 3.5 * susceptibility);

    // Blend: near the center, stripes are ordered; at the periphery, labyrinthine
    float r = length(p);
    float order = smoothstep(0.35, 0.1, r);
    float pattern = mix(warpedStripe, stripe, order);

    // Normalize to [0,1]
    return pattern * 0.5 + 0.5;
}

// ─── TRAVELING WAVE FRONT ────────────────────────────────────────────────────
// When field oscillates near resonance, a traveling WAVE rolls through the domain.
// It looks like a ripple of stripes moving across the pattern.
float travelingWave(vec2 p, float t) {
    vec2 H = fieldDirection(t);
    float wavefront = dot(p, H) * 8.0 - t * fieldOscillation * 5.0;
    float wave = sin(wavefront) * exp(-length(p) * 2.0);
    return wave * 0.5 + 0.5;
}

// ─── SOLITON PEAKS ───────────────────────────────────────────────────────────
// At the phase boundary (stripe ↔ spike regimes), isolated "magnetic solitons"
// appear — stable solitary peaks that nucleate in the domain wall intersections.
float solitonPeaks(vec2 p, float t) {
    float total = 0.0;
    for (int i = 0; i < 8; i++) {
        float fi    = float(i);
        vec2  seed  = vec2(hash1(fi) - 0.5, hash1(fi + 17.3) - 0.5) * 0.5;
        float phase = hash1(fi + 3.7) * 6.2831853;
        // Solitons drift slowly along the field direction
        vec2 H = laggedField(t);
        seed  += H * sin(t * 0.3 + phase) * 0.04;
        float d = length(p - seed);
        total += exp(-d * d * 60.0) * (0.5 + 0.5 * sin(t * 0.7 + phase));
    }
    return total;
}

// ─── MAIN ────────────────────────────────────────────────────────────────────
void main() {
    vec2 uv     = gl_FragCoord.xy / resolution;
    vec2 aspect = vec2(resolution.x / resolution.y, 1.0);
    vec2 p      = (uv - 0.5) * aspect;

    float domain  = labyrinthineDomain(p, time);
    float wave    = travelingWave(p, time);
    float soliton = solitonPeaks(p, time);

    // Combined surface height
    float h = domain * susceptibility / surfaceTension * 0.04 +
              wave   * 0.015 * magnetStrength / surfaceTension +
              soliton * 0.05;

    float baseLine = -0.05;
    float surface  = baseLine + h;
    float sdf      = p.y - surface;

    // ─── SHADING ─────────────────────────────────────────────────────────────
    float mask = smoothstep(0.006, -0.006, sdf);
    float edge = smoothstep(0.018, 0.0, abs(sdf));

    // Domain wall highlighting: the transition between stripe domains is brighter.
    // Domain walls correspond to points where |domain - 0.5| is small.
    float domainWall = smoothstep(0.15, 0.0, abs(domain - 0.5));
    vec3  wallGlow   = vec3(0.08, 0.14, 0.22) * domainWall * mask * 1.5;

    // Surface meniscus
    vec3 glint = edge * vec3(0.1, 0.15, 0.25);

    // Soliton peaks: bright isolated apex glow
    vec3 solitonGlow = vec3(0.15, 0.25, 0.4) * soliton * mask * 0.5;

    // Traveling wave crest highlights
    float waveBright = smoothstep(0.45, 0.5, wave) * smoothstep(0.55, 0.5, wave);
    vec3  waveGlow   = vec3(0.06, 0.12, 0.22) * waveBright * mask;

    vec3 col = glint + wallGlow + solitonGlow + waveGlow;
    vec3 bg  = vec3(0.0, 0.002, 0.007);
    col = mix(bg, col, mask + edge * 0.5);

    gl_FragColor = vec4(col, 1.0);
}
